/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import javax.swing.JButton;
import javax.swing.JComboBox;
import modelo.Reg_dataSocial;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author pc
 */
public class Ins_DatoSocialesEco extends javax.swing.JFrame {

    /**
     * Creates new form InscripcionDatoSocioEcon
     */
    public Ins_DatoSocialesEco() {
        initComponents();
        setLocationRelativeTo(null); 
        setTitle("Datos Socioeconómicos");
        this.setResizable(false);
         
        
    }

    
    public JButton getJbtn_guardarDatosSoeco() {
        return Jbtn_guardarDatosSoeco;
    }

    public void setJbtn_guardarDatosSoeco(JButton Jbtn_guardarDatosSoeco) {
        this.Jbtn_guardarDatosSoeco = Jbtn_guardarDatosSoeco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Jbtn_guardarDatosSoeco = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        Jtf_Fijo = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Jtf_Esporadico = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Jtf_Propio = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        Jtf_OtrosIngresos = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Jtf_TotalIngresos = new javax.swing.JTextField();
        Jtf_gastos = new javax.swing.JTextField();
        JCB_sustento = new javax.swing.JComboBox<>();
        jPanelColor = new javax.swing.JPanel();
        jLabImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(228, 244, 251));
        jPanel4.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel20.setText("Datos Socioeconómicos");

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel22.setText("Personas que sustentan el hogar:");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel23.setText("Tipo de trabajo:");

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel24.setText("Gastos mensuales:");

        Jbtn_guardarDatosSoeco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Jbtn_guardarDatosSoeco.setForeground(new java.awt.Color(51, 51, 51));
        Jbtn_guardarDatosSoeco.setText("Siguiente");
        Jbtn_guardarDatosSoeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardarDatoSoecoActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel25.setText("Fijo:");

        Jtf_Fijo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Fijo.setText("0");
        Jtf_Fijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_FijoActionPerformed(evt);
            }
        });
        Jtf_Fijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_FijoKeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel26.setText("Esporádicos:");

        Jtf_Esporadico.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Esporadico.setText("0");
        Jtf_Esporadico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_EsporadicoActionPerformed(evt);
            }
        });
        Jtf_Esporadico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_EsporadicoKeyTyped(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel27.setText("Propio:");

        Jtf_Propio.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Propio.setText("0");
        Jtf_Propio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_PropioActionPerformed(evt);
            }
        });
        Jtf_Propio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_PropioKeyTyped(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel28.setText("Otros:");

        Jtf_OtrosIngresos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_OtrosIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_OtrosIngresosActionPerformed(evt);
            }
        });
        Jtf_OtrosIngresos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_OtrosIngresosKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel29.setText("Total de ingresos:");

        Jtf_TotalIngresos.setEditable(false);
        Jtf_TotalIngresos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jtf_TotalIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TotalIngresosActionPerformed(evt);
            }
        });

        Jtf_gastos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jtf_gastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TotalIngresos1ActionPerformed(evt);
            }
        });
        Jtf_gastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_gastosKeyTyped(evt);
            }
        });

        JCB_sustento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madre", "Padre", " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)
                                        .addComponent(Jtf_OtrosIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(Jtf_TotalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(Jtf_Fijo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(Jtf_Esporadico, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Jtf_gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jtf_Propio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JCB_sustento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(Jbtn_guardarDatosSoeco)
                .addGap(446, 446, 446))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel20)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(JCB_sustento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel23)
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Jtf_Fijo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(Jtf_Esporadico, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(Jtf_Propio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(Jtf_OtrosIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(Jtf_TotalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtf_gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(55, 55, 55)
                .addComponent(Jbtn_guardarDatosSoeco)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jPanelColor.setBackground(new java.awt.Color(109, 146, 199));

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buenpastor.jpg"))); // NOI18N
        jPanel1.add(jLabImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtf_TotalIngresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TotalIngresos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TotalIngresos1ActionPerformed

    private void Jtf_TotalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TotalIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TotalIngresosActionPerformed

    private void Jtf_OtrosIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_OtrosIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_OtrosIngresosActionPerformed

    private void Jtf_PropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_PropioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_PropioActionPerformed

    private void Jtf_EsporadicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_EsporadicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_EsporadicoActionPerformed

    private void Jtf_FijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_FijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_FijoActionPerformed

    private void Jbtn_guardarDatoSoecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardarDatoSoecoActionPerformed
        // TODO add your handling code here:
        
//        agregarDatosSocialesEco();
//        this.setVisible(false);
        
        
       
        
    }//GEN-LAST:event_Jbtn_guardarDatoSoecoActionPerformed

    private void Jtf_FijoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_FijoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente numeros");
        }
    }//GEN-LAST:event_Jtf_FijoKeyTyped

    private void Jtf_EsporadicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_EsporadicoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente numeros");
        }
    }//GEN-LAST:event_Jtf_EsporadicoKeyTyped

    private void Jtf_PropioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_PropioKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente numeros");
        }
    }//GEN-LAST:event_Jtf_PropioKeyTyped

    private void Jtf_OtrosIngresosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_OtrosIngresosKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente numeros");
        }
    }//GEN-LAST:event_Jtf_OtrosIngresosKeyTyped

    private void Jtf_gastosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_gastosKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente numeros");
        }
    }//GEN-LAST:event_Jtf_gastosKeyTyped
    
    //Variables 
    String per_sustento, forma_trabajo, otros_ing, gast_mensual;
    int ingreso = 0;
    //Getter and setter 

    public String getPer_sustento() {
        return per_sustento;
    }

    public void setPer_sustento(String per_sustento) {
        this.per_sustento = per_sustento;
    }

    public int getIngreso() {
        return ingreso;
    }

    public void setIngreso(int ingreso) {
        this.ingreso = ingreso;
    }

    public String getForma_trabajo() {
        return forma_trabajo;
    }

    public void setForma_trabajo(String forma_trabajo) {
        this.forma_trabajo = forma_trabajo;
    }

    public String getOtros_ing() {
        return otros_ing;
    }

    public void setOtros_ing(String otros_ing) {
        this.otros_ing = otros_ing;
    }

    public String getGast_mensual() {
        return gast_mensual;
    }

    public void setGast_mensual(String gast_mensual) {
        this.gast_mensual = gast_mensual;
    }
    
    
    //Variables de ingreso
    public static int ingresos; 
    
    public void agregarDatosSocialesEco(){
        this.setForma_trabajo(formaTrabajo());
        this.setPer_sustento(this.JCB_sustento.getSelectedItem().toString());
        
        if (this.Jtf_OtrosIngresos.getText().equals("")){
            otros_ing = "Ninguno";
        }else{
            this.setOtros_ing(this.Jtf_OtrosIngresos.getText());
        }
        
        ingreso = calculoingreso(Integer.parseInt(Jtf_Fijo.getText()), Integer.parseInt(Jtf_Esporadico.getText()), Integer.parseInt(Jtf_Propio.getText()));
        //data_social.setPer_total_ingreso(calculoingreso(Integer.parseInt(Jtf_Fijo.getText()), Integer.parseInt(Jtf_Esporadico.getText()), Integer.parseInt(Jtf_Propio.getText()))); 
        this.setGast_mensual(this.Jtf_gastos.getText());
        Controlador ctrl = new Controlador();
        ctrl.cargaSocioEconomico(this.getForma_trabajo(), this.getPer_sustento(), this.getOtros_ing(),this.getGast_mensual());

        
        
    }

    public static int getIngresos() {
        return ingresos;
    }

    public static void setIngresos(int ingresos) {
        Ins_DatoSocialesEco.ingresos = ingresos;
    }

    public JComboBox<String> getJCB_sustento() {
        return JCB_sustento;
    }

    public void setJCB_sustento(JComboBox<String> JCB_sustento) {
        this.JCB_sustento = JCB_sustento;
    }

    public JTextField getJtf_Esporadico() {
        return Jtf_Esporadico;
    }

    public void setJtf_Esporadico(JTextField Jtf_Esporadico) {
        this.Jtf_Esporadico = Jtf_Esporadico;
    }

    public JTextField getJtf_Fijo() {
        return Jtf_Fijo;
    }

    public void setJtf_Fijo(JTextField Jtf_Fijo) {
        this.Jtf_Fijo = Jtf_Fijo;
    }

    public JTextField getJtf_OtrosIngresos() {
        return Jtf_OtrosIngresos;
    }

    public void setJtf_OtrosIngresos(JTextField Jtf_OtrosIngresos) {
        this.Jtf_OtrosIngresos = Jtf_OtrosIngresos;
    }

    public JTextField getJtf_Propio() {
        return Jtf_Propio;
    }

    public void setJtf_Propio(JTextField Jtf_Propio) {
        this.Jtf_Propio = Jtf_Propio;
    }

    public JTextField getJtf_TotalIngresos() {
        return Jtf_TotalIngresos;
    }

    public void setJtf_TotalIngresos(JTextField Jtf_TotalIngresos) {
        this.Jtf_TotalIngresos = Jtf_TotalIngresos;
    }

    public JTextField getJtf_gastos() {
        return Jtf_gastos;
    }

    public void setJtf_gastos(JTextField Jtf_gastos) {
        this.Jtf_gastos = Jtf_gastos;
    }
    public String formaTrabajo(){
        String tipo = "";
        if(Integer.parseInt(Jtf_Fijo.getText())> 0){
            tipo = "Fijo";
        }else if(Integer.parseInt(Jtf_Esporadico.getText())> 0){
            tipo = "Esporadico";
        }else if(Integer.parseInt(Jtf_Propio.getText())> 0){
            tipo = "Propio";
        }
        return tipo;
    }
    public int calculoingreso(int fijo, int esporadico, int propio){
        int total = fijo + esporadico + propio;
        this.Jtf_TotalIngresos.setText(Integer.toString(total));
        ingresos = total ;
        return total;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoSocialesEco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoSocialesEco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoSocialesEco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoSocialesEco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ins_DatoSocialesEco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCB_sustento;
    private javax.swing.JButton Jbtn_guardarDatosSoeco;
    private javax.swing.JTextField Jtf_Esporadico;
    private javax.swing.JTextField Jtf_Fijo;
    private javax.swing.JTextField Jtf_OtrosIngresos;
    private javax.swing.JTextField Jtf_Propio;
    private javax.swing.JTextField Jtf_TotalIngresos;
    private javax.swing.JTextField Jtf_gastos;
    private javax.swing.JLabel jLabImagen;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelColor;
    // End of variables declaration//GEN-END:variables
}
