/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import dao.DaoMama;
import dao.DaoPapa;
//import javafx.scene.control.ComboBox;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import modelo.Mama;
import modelo.Papa;

/**
 *
 * @author pc
 */
public class Ins_DatoPadre extends javax.swing.JFrame {

    
    /**
     * Creates new form InscripcionDatoSocioEcon
     */
    public Ins_DatoPadre() {
        initComponents();
        setBounds(125, 0, 1350, 845);
        setTitle("Datos de Padre"); 
        setLocationRelativeTo(null);        
        this.setResizable(false);
        this.BG_tutor_tipo.add(JRB_madre);
        this.BG_tutor_tipo.add(JRB_padre);
        
    }


    public JButton getJbtn_datosEscolares() {
        return Jbtn_datosEscolares;
    }

    public void setJbtn_datosEscolares(JButton Jbtn_datosEscolares) {
        this.Jbtn_datosEscolares = Jbtn_datosEscolares;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_tutor_tipo = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Jtf_nom_ape = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Jtf_lugar_trab = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Jtf_Cargo = new javax.swing.JTextField();
        Jtf_Tut_telef = new javax.swing.JTextField();
        JRB_madre = new javax.swing.JRadioButton();
        JRB_padre = new javax.swing.JRadioButton();
        Jcb_Estado = new javax.swing.JComboBox<>();
        Jbtn_datosEscolares = new javax.swing.JButton();
        jLabImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(228, 244, 251));
        jPanel4.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel20.setText("Datos de Padres");

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel22.setText("Parentesco:");

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel24.setText("Teléfono");

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel25.setText("Nombre y apellido:");

        Jtf_nom_ape.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_nom_ape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_FijoActionPerformed(evt);
            }
        });
        Jtf_nom_ape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_nom_apeKeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel26.setText("Estado civil:");

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel28.setText("Lugar de trabajo:");

        Jtf_lugar_trab.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_lugar_trab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_OtrosIngresosActionPerformed(evt);
            }
        });
        Jtf_lugar_trab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_lugar_trabKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel29.setText("Cargo:");

        Jtf_Cargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jtf_Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TotalIngresosActionPerformed(evt);
            }
        });
        Jtf_Cargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_CargoKeyTyped(evt);
            }
        });

        Jtf_Tut_telef.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jtf_Tut_telef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TotalIngresos1ActionPerformed(evt);
            }
        });

        JRB_madre.setBackground(new java.awt.Color(228, 244, 251));
        BG_tutor_tipo.add(JRB_madre);
        JRB_madre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JRB_madre.setText("Madre");
        JRB_madre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_madreActionPerformed(evt);
            }
        });

        JRB_padre.setBackground(new java.awt.Color(228, 244, 251));
        BG_tutor_tipo.add(JRB_padre);
        JRB_padre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JRB_padre.setSelected(true);
        JRB_padre.setText("Padre");
        JRB_padre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_padreActionPerformed(evt);
            }
        });

        Jcb_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Soltero", "Unión de hecho", "Divorciado", "Viudo", "Actualizar" }));

        Jbtn_datosEscolares.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_datosEscolares.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Jbtn_datosEscolares.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_datosEscolares.setText("Siguiente");
        Jbtn_datosEscolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_datosEscolaresJbtn_guardarDatoSoecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jtf_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jtf_lugar_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JRB_madre, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(JRB_padre, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel26)
                                        .addGap(24, 24, 24)
                                        .addComponent(Jcb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel20))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(Jtf_nom_ape, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jtf_Tut_telef, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jbtn_datosEscolares, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JRB_madre)
                            .addComponent(JRB_padre)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jcb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(Jtf_nom_ape, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(Jtf_lugar_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(Jtf_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jtf_Tut_telef, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(30, 30, 30)
                        .addComponent(Jbtn_datosEscolares, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(149, 149, 149))))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 910, 520));

        jLabImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buenpastor.jpg"))); // NOI18N
        getContentPane().add(jLabImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRB_padreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_padreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_padreActionPerformed

    private void JRB_madreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_madreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_madreActionPerformed

    private void Jtf_TotalIngresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TotalIngresos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TotalIngresos1ActionPerformed

    private void Jtf_CargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_CargoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente letras");
        }
    }//GEN-LAST:event_Jtf_CargoKeyTyped

    private void Jtf_TotalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TotalIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TotalIngresosActionPerformed

    private void Jtf_lugar_trabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_lugar_trabKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente letras");
        }
    }//GEN-LAST:event_Jtf_lugar_trabKeyTyped

    private void Jtf_OtrosIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_OtrosIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_OtrosIngresosActionPerformed

    private void Jtf_nom_apeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_nom_apeKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente letras");
        }
    }//GEN-LAST:event_Jtf_nom_apeKeyTyped

    private void Jtf_FijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_FijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_FijoActionPerformed

    private void Jbtn_datosEscolaresJbtn_guardarDatoSoecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_datosEscolaresJbtn_guardarDatoSoecoActionPerformed
        // TODO add your handling code here:
        //agregarTutor();
        //agregarGeneralTutor();
//        Ins_DatoSocialesEco data_eco = new Ins_DatoSocialesEco();
//        data_eco.setVisible(true);
    }//GEN-LAST:event_Jbtn_datosEscolaresJbtn_guardarDatoSoecoActionPerformed
    
/*
    public void agregarTutor(){//Aqui se ingresa en las tablas tanto de padre como de madre segun se elija
        DaoMama daoma= new DaoMama();
        DaoPapa daopa= new DaoPapa();
        Reg_Padres tutor = new Reg_Padres();
        if(JRB_madre.isSelected()){
            tutor.setTut_tipo("Madre");
           
            tutor.setId_madre(1);
            tutor.setTut_nom_ape(this.Jtf_nom_ape.getText());
            tutor.setTut_estado(this.Jcb_Estado.getSelectedItem().toString());
            tutor.setTut_trabajo(this.Jtf_lugar_trab.getText());
            tutor.setTut_cargo(this.Jtf_Cargo.getText());
            tutor.setTut_cel(this.Jtf_Tut_telef.getText());
            tutor.setTutor_ingresos(Ins_DatoSocialesEco.ingresos);
            agregarGeneralTutor();
            tutor.mostrarDato();
        }
        else if(JRB_padre.isSelected()){
            tutor.setTut_tipo("Padre");
            tutor.setId_padre(1);
            tutor.setTut_nom_ape(this.Jtf_nom_ape.getText());
            tutor.setTut_estado(this.Jcb_Estado.getSelectedItem().toString());
            tutor.setTut_trabajo(this.Jtf_lugar_trab.getText());
            tutor.setTut_cargo(this.Jtf_Cargo.getText());
            tutor.setTut_cel(this.Jtf_Tut_telef.getText());
            tutor.setTutor_ingresos(Ins_DatoSocialesEco.ingresos);
            tutor.mostrarDato();
        }
        
        
        
        
        /*if(JRB_madre.isSelected()){
            tutor.setTut_tipo("Madre");
            tutor.setId_madre(1);
            tutor.setTut_nom_ape(this.Jtf_nom_ape.getText());
            tutor.setTut_estado(this.Jcb_Estado.getSelectedItem().toString());
            tutor.setTut_trabajo(this.Jtf_lugar_trab.getText());
            tutor.setTut_cargo(this.Jtf_Cargo.getText());
            tutor.setTut_cel(this.Jtf_Tut_telef.getText());
            tutor.setTutor_ingresos(Ins_DatoSocialesEco.ingresos);
            agregarGeneralTutor();
            tutor.mostrarDato();
        }
        else if(JRB_padre.isSelected()){
            tutor.setTut_tipo("Padre");
            tutor.setId_padre(1);
            tutor.setTut_nom_ape(this.Jtf_nom_ape.getText());
            tutor.setTut_estado(this.Jcb_Estado.getSelectedItem().toString());
            tutor.setTut_trabajo(this.Jtf_lugar_trab.getText());
            tutor.setTut_cargo(this.Jtf_Cargo.getText());
            tutor.setTut_cel(this.Jtf_Tut_telef.getText());
            tutor.setTutor_ingresos(Ins_DatoSocialesEco.ingresos);
            tutor.mostrarDato();
        }
    }*/
    
    /*public void agregarGeneralTutor(){
        Reg_Padres tutor = new Reg_Padres();
        tutor.setId_tutor(1);
        tutor.setId_padre(1);
        tutor.setId_madre(1);     
    }*/
    
    public void inscribir_datoSocioEconomico(){
        Ins_DatoSocialesEco data_eco = new Ins_DatoSocialesEco();
        data_eco.setVisible(true);
        
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ins_DatoPadre().setVisible(true);
            }
        });
    }

    public ButtonGroup getBG_tutor_tipo() {
        return BG_tutor_tipo;
    }

    public void setBG_tutor_tipo(ButtonGroup BG_tutor_tipo) {
        this.BG_tutor_tipo = BG_tutor_tipo;
    }

    public JRadioButton getJRB_madre() {
        return JRB_madre;
    }

    public void setJRB_madre(JRadioButton JRB_madre) {
        this.JRB_madre = JRB_madre;
    }

    public JRadioButton getJRB_padre() {
        return JRB_padre;
    }

    public void setJRB_padre(JRadioButton JRB_padre) {
        this.JRB_padre = JRB_padre;
    }

    public JComboBox<String> getJcb_Estado() {
        return Jcb_Estado;
    }

    public void setJcb_Estado(JComboBox<String> Jcb_Estado) {
        this.Jcb_Estado = Jcb_Estado;
    }

    public JTextField getJtf_Cargo() {
        return Jtf_Cargo;
    }

    public void setJtf_Cargo(JTextField Jtf_Cargo) {
        this.Jtf_Cargo = Jtf_Cargo;
    }

    public JTextField getJtf_Tut_telef() {
        return Jtf_Tut_telef;
    }

    public void setJtf_Tut_telef(JTextField Jtf_Tut_telef) {
        this.Jtf_Tut_telef = Jtf_Tut_telef;
    }

    public JTextField getJtf_lugar_trab() {
        return Jtf_lugar_trab;
    }

    public void setJtf_lugar_trab(JTextField Jtf_lugar_trab) {
        this.Jtf_lugar_trab = Jtf_lugar_trab;
    }

    public JTextField getJtf_nom_ape() {
        return Jtf_nom_ape;
    }

    public void setJtf_nom_ape(JTextField Jtf_nom_ape) {
        this.Jtf_nom_ape = Jtf_nom_ape;
    }

    

    public void llenarDatosPa(Papa modePa ) {
        getJtf_nom_ape().setText(modePa.getNombre());
        String estCivil =modePa.getEst_civ_pa();
        getJcb_Estado().setSelectedItem(estCivil);
        getJtf_lugar_trab().setText(modePa.getLug_tra_pa());
        getJtf_Cargo().setText(modePa.getCargo_pa());
        getJtf_Tut_telef().setText(modePa.getTelefono());
        getJtf_nom_ape().setText(modePa.getNombre());
        getJcb_Estado().setSelectedItem(estCivil);
        getJtf_lugar_trab().setText(modePa.getLug_tra_pa());
        getJtf_Cargo().setText(modePa.getCargo_pa());
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG_tutor_tipo;
    public javax.swing.JRadioButton JRB_madre;
    public javax.swing.JRadioButton JRB_padre;
    private javax.swing.JButton Jbtn_datosEscolares;
    private javax.swing.JComboBox<String> Jcb_Estado;
    private javax.swing.JTextField Jtf_Cargo;
    private javax.swing.JTextField Jtf_Tut_telef;
    private javax.swing.JTextField Jtf_lugar_trab;
    private javax.swing.JTextField Jtf_nom_ape;
    private javax.swing.JLabel jLabImagen;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
