/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import modelo.Reg_Escolar;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author pc
 */
public class Ins_DatoEscolar extends javax.swing.JFrame {

    /**
     * Creates new form InscripcionDatoSocioEcon
     */
    public Ins_DatoEscolar() {
        initComponents();
        setBounds(125, 0, 1350, 845);
        setTitle("Datos Escolares");
        setLocationRelativeTo(null);        
        this.setResizable(false);
        this.BG_escolaridad.add(JRB_primaria);
        this.BG_escolaridad.add(JRB_secundaria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_escolaridad = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Jbtn_guardarDatosFinal = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Jtf_NombreDocente = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Jtf_Cel = new javax.swing.JTextField();
        Jtf_DireEscolar = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Jtf_NombInst = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        JRB_primaria = new javax.swing.JRadioButton();
        JRB_secundaria = new javax.swing.JRadioButton();
        btnVisualizarTabla = new javax.swing.JButton();
        jCmBGrado = new javax.swing.JComboBox();
        jLabImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(228, 244, 251));
        jPanel4.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel20.setText("Datos Escolares");

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel24.setText("Direccion escolar:");

        Jbtn_guardarDatosFinal.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_guardarDatosFinal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Jbtn_guardarDatosFinal.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_guardarDatosFinal.setText("Guardar");
        Jbtn_guardarDatosFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardarDatosFinalJbtn_guardarDatoSoecoActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel25.setText("Nombre de la  institución:"); // NOI18N

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel28.setText("Nombre del docente:");

        Jtf_NombreDocente.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_NombreDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_NombreDocenteJtf_OtrosIngresosActionPerformed(evt);
            }
        });
        Jtf_NombreDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_NombreDocenteKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel29.setText("Teléfono:");

        Jtf_Cel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jtf_Cel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_CelJtf_TotalIngresosActionPerformed(evt);
            }
        });

        Jtf_DireEscolar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jtf_DireEscolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_DireEscolarJtf_TotalIngresos1ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel26.setText("Grado:"); // NOI18N

        Jtf_NombInst.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_NombInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_NombInstJtf_FijoActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel30.setText("Nivel escolar:");

        JRB_primaria.setBackground(new java.awt.Color(228, 244, 251));
        BG_escolaridad.add(JRB_primaria);
        JRB_primaria.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JRB_primaria.setSelected(true);
        JRB_primaria.setText("Primaria");
        JRB_primaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_primariaActionPerformed(evt);
            }
        });

        JRB_secundaria.setBackground(new java.awt.Color(228, 244, 251));
        BG_escolaridad.add(JRB_secundaria);
        JRB_secundaria.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JRB_secundaria.setText("Secundaria");
        JRB_secundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_secundariaActionPerformed(evt);
            }
        });

        btnVisualizarTabla.setBackground(new java.awt.Color(71, 82, 94));
        btnVisualizarTabla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVisualizarTabla.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarTabla.setText("Visualizar Registros");
        btnVisualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarTablaJbtn_CancelarDatoSoecoActionPerformed(evt);
            }
        });

        jCmBGrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7 mo ", "8 vo", "9 no" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addComponent(jLabel20))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel29)
                                    .addGap(18, 18, 18)
                                    .addComponent(Jtf_Cel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVisualizarTabla))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel30)
                                    .addGap(18, 18, 18)
                                    .addComponent(JRB_primaria)
                                    .addGap(18, 18, 18)
                                    .addComponent(JRB_secundaria)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                    .addComponent(jLabel26)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCmBGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel21)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(51, 51, 51)))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Jtf_DireEscolar, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                                        .addComponent(Jtf_NombInst)
                                        .addComponent(Jtf_NombreDocente))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(Jbtn_guardarDatosFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel20)
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRB_primaria)
                    .addComponent(JRB_secundaria)
                    .addComponent(jLabel26)
                    .addComponent(jLabel30)
                    .addComponent(jCmBGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Jtf_NombInst, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtf_DireEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtf_NombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtf_Cel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(btnVisualizarTabla))
                .addGap(43, 43, 43)
                .addComponent(Jbtn_guardarDatosFinal)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 990, 530));

        jLabImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buenpastor.jpg"))); // NOI18N
        getContentPane().add(jLabImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtf_DireEscolarJtf_TotalIngresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_DireEscolarJtf_TotalIngresos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_DireEscolarJtf_TotalIngresos1ActionPerformed

    private void Jtf_CelJtf_TotalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_CelJtf_TotalIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_CelJtf_TotalIngresosActionPerformed

    private void Jtf_NombreDocenteJtf_OtrosIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_NombreDocenteJtf_OtrosIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_NombreDocenteJtf_OtrosIngresosActionPerformed

    private void Jbtn_guardarDatosFinalJbtn_guardarDatoSoecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardarDatosFinalJbtn_guardarDatoSoecoActionPerformed
        // TODO add your handling code here:
       // registroescolar();
    }//GEN-LAST:event_Jbtn_guardarDatosFinalJbtn_guardarDatoSoecoActionPerformed

    private void Jtf_NombInstJtf_FijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_NombInstJtf_FijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_NombInstJtf_FijoActionPerformed

    private void JRB_primariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_primariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_primariaActionPerformed

    private void JRB_secundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_secundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_secundariaActionPerformed

    private void Jtf_NombreDocenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_NombreDocenteKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente letras");
        }
    }//GEN-LAST:event_Jtf_NombreDocenteKeyTyped

    private void btnVisualizarTablaJbtn_CancelarDatoSoecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarTablaJbtn_CancelarDatoSoecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisualizarTablaJbtn_CancelarDatoSoecoActionPerformed

    public JRadioButton getJRB_primaria() {
        return JRB_primaria;
    }

    public void setJRB_primaria(JRadioButton JRB_primaria) {
        this.JRB_primaria = JRB_primaria;
    }

    public JRadioButton getJRB_secundaria() {
        return JRB_secundaria;
    }

    public void setJRB_secundaria(JRadioButton JRB_secundaria) {
        this.JRB_secundaria = JRB_secundaria;
    }

    public JTextField getJtf_Cel() {
        return Jtf_Cel;
    }

    public void setJtf_Cel(JTextField Jtf_Cel) {
        this.Jtf_Cel = Jtf_Cel;
    }

    public JTextField getJtf_DireEscolar() {
        return Jtf_DireEscolar;
    }

    public void setJtf_DireEscolar(JTextField Jtf_DireEscolar) {
        this.Jtf_DireEscolar = Jtf_DireEscolar;
    }

    public JTextField getJtf_NombInst() {
        return Jtf_NombInst;
    }

    public void setJtf_NombInst(JTextField Jtf_NombInst) {
        this.Jtf_NombInst = Jtf_NombInst;
    }

    public JTextField getJtf_NombreDocente() {
        return Jtf_NombreDocente;
    }

    public void setJtf_NombreDocente(JTextField Jtf_NombreDocente) {
        this.Jtf_NombreDocente = Jtf_NombreDocente;
    }

  
    public JButton getJbtn_guardarDatosFinal() {
        return Jbtn_guardarDatosFinal;
    }

    public void setJbtn_guardarDatosFinal(JButton Jbtn_guardarDatosFinal) {
        this.Jbtn_guardarDatosFinal = Jbtn_guardarDatosFinal;
    }
    

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ins_DatoEscolar().setVisible(true);
            }
        });
    }

    public JButton getBtnVisualizarTabla() {
        return btnVisualizarTabla;
    }

    public JComboBox getjCmBGrado() {
        return jCmBGrado;
    }

    public void setjCmBGrado(JComboBox jCmBGrado) {
        this.jCmBGrado = jCmBGrado;
    }

    public void llenarGrdPrima() {
        jCmBGrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Actualizar", "Inicial 1", "Inicial 2", "1ero Básica","2do Básica", 
                                                                                    "3ero Básica", "4to Básica", "5to Básica", "6to Básica", "7to Básica" }));
    }
    public void llenarGrdSecun() {
        jCmBGrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Actualizar", "8vo EGB ", "9no EGB ", "10mo EGB", "1ero Bachillerato ", "2do Bachillerato ", "3ero Bachillerato" }));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG_escolaridad;
    private javax.swing.JRadioButton JRB_primaria;
    private javax.swing.JRadioButton JRB_secundaria;
    private javax.swing.JButton Jbtn_guardarDatosFinal;
    private javax.swing.JTextField Jtf_Cel;
    private javax.swing.JTextField Jtf_DireEscolar;
    private javax.swing.JTextField Jtf_NombInst;
    private javax.swing.JTextField Jtf_NombreDocente;
    private javax.swing.JButton btnVisualizarTabla;
    private javax.swing.JComboBox jCmBGrado;
    private javax.swing.JLabel jLabImagen;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
