/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import javax.swing.JButton;
import javax.swing.JTable;
import vista.Crear_NuevoUsuario;

/**
 *
 * @author CGCF
 */
public class List_Padres extends javax.swing.JFrame {

    /**
     * Creates new form ListaUsuario
     */
    public List_Padres() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Lista de usuarios");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton_AgregarPadr = new javax.swing.JButton();
        jButton_Consultar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtab_Lst_Padres = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(228, 244, 251));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(228, 244, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_AgregarPadr.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton_AgregarPadr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new_add_user_.png"))); // NOI18N
        jButton_AgregarPadr.setText("Agregar ");
        jButton_AgregarPadr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AgregarPadr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AgregarPadr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarPadrActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_AgregarPadr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 140, 130));

        jButton_Consultar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save.png"))); // NOI18N
        jButton_Consultar.setText("Consultar");
        jButton_Consultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Consultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 140, 130));

        Jtab_Lst_Padres.setAutoCreateRowSorter(true);
        Jtab_Lst_Padres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtab_Lst_Padres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Maria", "Casada", "Guayaquil", "Administrador", "233458"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Estado Civil", "Lugar de Trabajo", "Cargo", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Jtab_Lst_Padres);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 620, 190));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel12.setText("Lista de Padres");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ConsultarActionPerformed

    private void jButton_AgregarPadrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarPadrActionPerformed

    }//GEN-LAST:event_jButton_AgregarPadrActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_Padres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_Padres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_Padres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_Padres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List_Padres().setVisible(true);
            }
        });
    }
    

    public JTable getJtab_Lst_Padres() {
        return Jtab_Lst_Padres;
    }

    public void setJtab_Lst_Padres(JTable Jtab_Lst_Padres) {
        this.Jtab_Lst_Padres = Jtab_Lst_Padres;
    }

    public JButton getjButton_AgregarPadr() {
        return jButton_AgregarPadr;
    }

    public void setjButton_AgregarPadr(JButton jButton_AgregarPadr) {
        this.jButton_AgregarPadr = jButton_AgregarPadr;
    }

    public JButton getjButton_EditarDatos() {
        return jButton_Consultar;
    }

    public void setjButton_EditarDatos(JButton jButton_EditarDatos) {
        this.jButton_Consultar = jButton_EditarDatos;
    }

    public JButton getjButton_Consultar() {
        return jButton_Consultar;
    }

    public void setjButton_Consultar(JButton jButton_Consultar) {
        this.jButton_Consultar = jButton_Consultar;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Jtab_Lst_Padres;
    public javax.swing.JButton jButton_AgregarPadr;
    public javax.swing.JButton jButton_Consultar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}

