/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JLabel;
import modelo.ExportarExcel;

/**
 *
 * @author pc
 */
public class Lista_Beneficiarios extends javax.swing.JFrame {

    /**
     * Creates new form Lista_Beneficiarios
     */
    public Lista_Beneficiarios() {
        initComponents();
        setTitle("Lista de Beneficiarios");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBttn_AgregarBenefi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtab_LstBeneficiario = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLbIngresarTexto = new javax.swing.JLabel();
        jLblIngresarNumBenefi1 = new javax.swing.JLabel();
        jLblRetroceder = new javax.swing.JLabel();
        jBttn_editarBenef = new javax.swing.JButton();
        jBttn_asignarCurso = new javax.swing.JButton();
        JBTN_exportar = new javax.swing.JButton();
        JBTN_exportarPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 244, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBttn_AgregarBenefi.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jBttn_AgregarBenefi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        jBttn_AgregarBenefi.setText("Agregar Beneficiario");
        jBttn_AgregarBenefi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttn_AgregarBenefi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttn_AgregarBenefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttn_AgregarBenefiActionPerformed(evt);
            }
        });
        jPanel1.add(jBttn_AgregarBenefi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 170, 130));

        Jtab_LstBeneficiario.setAutoCreateRowSorter(true);
        Jtab_LstBeneficiario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtab_LstBeneficiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombres", "Apellidos", "Direccion", "Telefono", "Padre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Jtab_LstBeneficiario);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1170, 320));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel12.setText("Lista de Beneficiarios");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLbIngresarTexto.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel1.add(jLbIngresarTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 200, 20));

        jLblIngresarNumBenefi1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(jLblIngresarNumBenefi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 80, 70, 20));

        jLblRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retroceso.png"))); // NOI18N
        jPanel1.add(jLblRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jBttn_editarBenef.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jBttn_editarBenef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jBttn_editarBenef.setText("Editar");
        jBttn_editarBenef.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttn_editarBenef.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttn_editarBenef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttn_editarBenefActionPerformed(evt);
            }
        });
        jPanel1.add(jBttn_editarBenef, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 170, 130));

        jBttn_asignarCurso.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jBttn_asignarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stamped.png"))); // NOI18N
        jBttn_asignarCurso.setText("Asignar curso");
        jBttn_asignarCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBttn_asignarCurso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBttn_asignarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttn_asignarCursoActionPerformed(evt);
            }
        });
        jPanel1.add(jBttn_asignarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 450, 170, 130));

        JBTN_exportar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JBTN_exportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.png"))); // NOI18N
        JBTN_exportar.setText("Exportar a excel");
        JBTN_exportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBTN_exportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBTN_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_exportarActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN_exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 170, 130));

        JBTN_exportarPDF.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JBTN_exportarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf-icon.png"))); // NOI18N
        JBTN_exportarPDF.setText("Exportar a pdf");
        JBTN_exportarPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBTN_exportarPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBTN_exportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_exportarPDFActionPerformed(evt);
            }
        });
        jPanel1.add(JBTN_exportarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 170, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttn_AgregarBenefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttn_AgregarBenefiActionPerformed
//        agregar_Beneficiario();
//        this.setVisible(false);
    }//GEN-LAST:event_jBttn_AgregarBenefiActionPerformed

    private void jBttn_editarBenefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttn_editarBenefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBttn_editarBenefActionPerformed

    private void jBttn_asignarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttn_asignarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBttn_asignarCursoActionPerformed

    private void JBTN_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_exportarActionPerformed
        ExportarExcel obj;
        try {
            obj = new ExportarExcel();
            obj.exportarExcel(Jtab_LstBeneficiario);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_JBTN_exportarActionPerformed

    private void JBTN_exportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_exportarPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBTN_exportarPDFActionPerformed
    
    public void agregar_Beneficiario(){
        Ins_Personal btnDatospersonal = new Ins_Personal();
        btnDatospersonal.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista_Beneficiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista_Beneficiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista_Beneficiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista_Beneficiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista_Beneficiarios().setVisible(true);
            }
        });
    }

    public JButton getjBttn_AgregarBenefi() {
        return jBttn_AgregarBenefi;
    }

    public void setjBttn_AgregarBenefi(JButton jBttn_AgregarBenefi) {
        this.jBttn_AgregarBenefi = jBttn_AgregarBenefi;
    }

    public JLabel getjLblRetroceder() {
        return jLblRetroceder;
    }

    public void setjLblRetroceder(JLabel jLblRetroceder) {
        this.jLblRetroceder = jLblRetroceder;
    }

    public JButton getjBttn_editarBenef() {
        return jBttn_editarBenef;
    }

    public void setjBttn_editarBenef(JButton jBttn_editarBenef) {
        this.jBttn_editarBenef = jBttn_editarBenef;
    }

    public JLabel getjLbIngresarTexto() {
        return jLbIngresarTexto;
    }

    public void setjLbIngresarTexto(JLabel jLbIngresarTexto) {
        this.jLbIngresarTexto = jLbIngresarTexto;
    }

    public JLabel getjLblIngresarNumBenefi1() {
        return jLblIngresarNumBenefi1;
    }

    public void setjLblIngresarNumBenefi1(JLabel jLblIngresarNumBenefi1) {
        this.jLblIngresarNumBenefi1 = jLblIngresarNumBenefi1;
    }

    public JButton getjBttn_asignarCurso() {
        return jBttn_asignarCurso;
    }

    public void setjBttn_asignarCurso(JButton jBttn_asignarCurso) {
        this.jBttn_asignarCurso = jBttn_asignarCurso;
    }

    public JButton getJBTN_exportarPDF() {
        return JBTN_exportarPDF;
    }

    public void setJBTN_exportarPDF(JButton JBTN_exportarPDF) {
        this.JBTN_exportarPDF = JBTN_exportarPDF;
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTN_exportar;
    private javax.swing.JButton JBTN_exportarPDF;
    public javax.swing.JTable Jtab_LstBeneficiario;
    private javax.swing.JButton jBttn_AgregarBenefi;
    private javax.swing.JButton jBttn_asignarCurso;
    private javax.swing.JButton jBttn_editarBenef;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLbIngresarTexto;
    private javax.swing.JLabel jLblIngresarNumBenefi1;
    private javax.swing.JLabel jLblRetroceder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
