/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.Color;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.ExportarExcel;
import modelo.Usuario;


/**
 *
 * @author CGCF
 */
public class List_Usuario extends javax.swing.JFrame {
    DefaultTableModel modelo;
    Usuario usuario;
    /**
     * Creates new form ListaUsuario
     */
    public List_Usuario() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Lista de usuarios");
        
    }
    
    private void encabezado(){
        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Usuario nnn");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Tipo");
        modelo.addColumn("Estado");
        this.Jtab_Lst_Usu.setModel(modelo);
        
//        jBtn_retroceder.setBackground(Color.GREEN);
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jButton_AgregarUsu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtab_Lst_Usu = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButton_EditarDatos = new javax.swing.JButton();
        jLblRetroceder = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(228, 244, 251));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(228, 244, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_AgregarUsu.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton_AgregarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new_add_user_.png"))); // NOI18N
        jButton_AgregarUsu.setText("Agregar Usuario");
        jButton_AgregarUsu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AgregarUsu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AgregarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarUsuActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_AgregarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 140, 130));

        Jtab_Lst_Usu.setAutoCreateRowSorter(true);
        Jtab_Lst_Usu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Jtab_Lst_Usu.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        Jtab_Lst_Usu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Ana Maria", null, "Administrador", "Activo"},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Usuario", "Contraseña", "Tipo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Jtab_Lst_Usu);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 600, 230));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel12.setText("Lista de Usuarios");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jButton_EditarDatos.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton_EditarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        jButton_EditarDatos.setText("Editar Datos");
        jButton_EditarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_EditarDatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_EditarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_EditarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 140, 130));

        jLblRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retroceso.png"))); // NOI18N
        jPanel1.add(jLblRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AgregarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarUsuActionPerformed

    }//GEN-LAST:event_jButton_AgregarUsuActionPerformed

    private void jButton_EditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_EditarDatosActionPerformed

    public JTable getJtab_Lst_Usu() {
        return Jtab_Lst_Usu;
    }

    public JLabel getjLblRetroceder() {
        return jLblRetroceder;
    }

    public void setjLblRetroceder(JLabel jLblRetroceder) {
        this.jLblRetroceder = jLblRetroceder;
    }

    public void setJtab_Lst_Usu(JTable Jtab_Lst_Usu) {
        this.Jtab_Lst_Usu = Jtab_Lst_Usu;
    }

    
    public JButton getjButton_AgregarUsu() {
        return jButton_AgregarUsu;
    }

    public void setjButton_AgregarUsu(JButton jButton_AgregarUsu) {
        this.jButton_AgregarUsu = jButton_AgregarUsu;
    }

    public JButton getjButton_EditarDatos1() {
        return jButton_EditarDatos;
    }

    public void setjButton_EditarDatos1(JButton jButton_EditarDatos1) {
        this.jButton_EditarDatos = jButton_EditarDatos1;
    }
 
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new List_Usuario().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Jtab_Lst_Usu;
    private javax.swing.JButton jButton_AgregarUsu;
    private javax.swing.JButton jButton_EditarDatos;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLblRetroceder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
