/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author florm
 */
public class ListaDatosEscolar extends javax.swing.JFrame {

    /**
     * Creates new form ListaDatosEscolar
     */
    public ListaDatosEscolar() {
        initComponents();
        
        setTitle("Lista de datos escolares");
        setLocationRelativeTo(null);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        totalRegistrados = new javax.swing.JLabel();
        RespuestaRegistrados = new javax.swing.JLabel();
        jButton_EditarDatos = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(228, 244, 251));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(228, 244, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_Estudiante", "Escolaridad", "Nombre_Escuela", "Grado", "Nombre Profesor", "Telefono Profesor", "Direccion Escuela"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 790, 260));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 70, 30));
        jPanel1.add(totalRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 210, 30));
        jPanel1.add(RespuestaRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 30, 20));

        jButton_EditarDatos.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton_EditarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save.png"))); // NOI18N
        jButton_EditarDatos.setText("Editar Datos");
        jButton_EditarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_EditarDatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_EditarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_EditarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 140, 130));

        btnRegresar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(204, 204, 204));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retroceso.png"))); // NOI18N
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_EditarDatosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDatosEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDatosEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDatosEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDatosEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDatosEscolar().setVisible(true);
            }
        });
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public JTable getTabla() {
        return tabla;
    }

    public void setTablaaa(JTable tablaaa) {
        this.tabla = tablaaa;
    }

    public JLabel getRespuestaRegistrados() {
        return RespuestaRegistrados;
    }

    public void setRespuestaRegistrados(JLabel RespuestaRegistrados) {
        this.RespuestaRegistrados = RespuestaRegistrados;
    }

    public JLabel getTotalRegistrados() {
        return totalRegistrados;
    }

    public void setTotalRegistrados(JLabel totalRegistrados) {
        this.totalRegistrados = totalRegistrados;
    }

    public JButton getjBtn_EditarDatos() {
        return jButton_EditarDatos;
    }

    public void setjBtn_EditarDatos(JButton jButton_EditarDatos) {
        this.jButton_EditarDatos = jButton_EditarDatos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RespuestaRegistrados;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton_EditarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel totalRegistrados;
    // End of variables declaration//GEN-END:variables
}
