/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Sebastian Riofrio
 */
public class Registro_Curso extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Registro_Curso() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cursos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jbtn_agrCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtbl_Asignaturas = new javax.swing.JTable();
        Jbtn_Editar = new javax.swing.JButton();
        jLblRetroceder = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(228, 244, 251));

        jPanel2.setBackground(new java.awt.Color(228, 244, 251));
        jPanel2.setPreferredSize(new java.awt.Dimension(680, 490));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("Cursos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        Jbtn_agrCurso.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Jbtn_agrCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        Jbtn_agrCurso.setText("Agregar Curso");
        Jbtn_agrCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Jbtn_agrCurso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Jbtn_agrCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jbtn_agrCursoMouseClicked(evt);
            }
        });
        Jbtn_agrCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_agrCursoActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn_agrCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 120));

        Jtbl_Asignaturas.setAutoCreateRowSorter(true);
        Jtbl_Asignaturas.setBackground(new java.awt.Color(228, 244, 251));
        Jtbl_Asignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Curso", "Estado", "Dirigido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Jtbl_Asignaturas.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(Jtbl_Asignaturas);
        Jtbl_Asignaturas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 660, 150));

        Jbtn_Editar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Jbtn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        Jbtn_Editar.setText("Editar");
        Jbtn_Editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Jbtn_Editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Jbtn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_EditarActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 120, 120));

        jLblRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retroceso.png"))); // NOI18N
        jPanel2.add(jLblRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_agrCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_agrCursoActionPerformed
    
    }//GEN-LAST:event_Jbtn_agrCursoActionPerformed

    private void Jbtn_agrCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jbtn_agrCursoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_agrCursoMouseClicked

    private void Jbtn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_EditarActionPerformed

//    public void registrarAsistencia(){
//        Asistencia_Curso btnAsistencia = new Asistencia_Curso();
//        btnAsistencia.setVisible(true);
//    }
    
    public void agregarCurso(){
        Crear_NuevoCurso btnAgregarCurso = new Crear_NuevoCurso();
        btnAgregarCurso.setVisible(true);
    }

    public JButton getJbtn_agrCurso() {
        return Jbtn_agrCurso;
    }

    public void setJbtn_agrCurso(JButton Jbtn_agrCurso) {
        this.Jbtn_agrCurso = Jbtn_agrCurso;
    }

    public JButton getJbtn_guardar() {
        return Jbtn_Editar;
    }

    public void setJbtn_guardar(JButton Jbtn_guardar) {
        this.Jbtn_Editar = Jbtn_guardar;
    }
    
    public void salir(){
        vista.Registrar_Asistencia btnsalir = new vista.Registrar_Asistencia();
        btnsalir.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Curso().setVisible(true);
            }
        });
    }

    public JButton getJbtn_Editar() {
        return Jbtn_Editar;
    }

    public void setJbtn_Editar(JButton Jbtn_Editar) {
        this.Jbtn_Editar = Jbtn_Editar;
    }

    public JLabel getjLblRetroceder() {
        return jLblRetroceder;
    }

    public void setjLblRetroceder(JLabel jLblRetroceder) {
        this.jLblRetroceder = jLblRetroceder;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Editar;
    public javax.swing.JButton Jbtn_agrCurso;
    public javax.swing.JTable Jtbl_Asignaturas;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblRetroceder;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
