/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;

/**
 *
 * @author wjoan
 */
public class Reports2 extends javax.swing.JFrame {

    /**
     * Creates new form Reports2
     */
    public Reports2() {
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.setResizable(false); 
        ButtonGroup botones = new ButtonGroup();
        botones.add(jRadioButtonReportsForCourses);
        botones.add(jRadioButtonReportsGeneral);

        
   
    }

    public JButton getjButtonGenerarReportsss() {
        return jButtonGenerarReportsss;
    }

    public void setjButtonGenerarReportsss(JButton jButtonGenerarReportsss) {
        this.jButtonGenerarReportsss = jButtonGenerarReportsss;
    }

    public JRadioButton getjRadioButtonReportsForCourses() {
        return jRadioButtonReportsForCourses;
    }

    public void setjRadioButtonReportsForCourses(JRadioButton jRadioButtonReportsForCourses) {
        this.jRadioButtonReportsForCourses = jRadioButtonReportsForCourses;
    }

    public JRadioButton getjRadioButtonReportsGeneral() {
        return jRadioButtonReportsGeneral;
    }

    public void setjRadioButtonReportsGeneral(JRadioButton jRadioButtonReportsGeneral) {
        this.jRadioButtonReportsGeneral = jRadioButtonReportsGeneral;
    }

    public ButtonGroup getBotones() {
        return botones;
    }

    public void setBotones(ButtonGroup botones) {
        this.botones = botones;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        botones = new javax.swing.ButtonGroup();
        jRadioButtonReportsForCourses = new javax.swing.JRadioButton();
        jRadioButtonReportsGeneral = new javax.swing.JRadioButton();
        jButtonGenerarReportsss = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jRadioButtonReportsForCourses.setText("Reporte por curso");

        jRadioButtonReportsGeneral.setText("Reporte General");

        jButtonGenerarReportsss.setText("Generar");
        jButtonGenerarReportsss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarReportsssActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonReportsGeneral)
                    .addComponent(jRadioButtonReportsForCourses))
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButtonGenerarReportsss)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jRadioButtonReportsForCourses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonReportsGeneral)
                .addGap(18, 18, 18)
                .addComponent(jButtonGenerarReportsss)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarReportsssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarReportsssActionPerformed
        
    }//GEN-LAST:event_jButtonGenerarReportsssActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton jButtonGenerarReportsss;
    private javax.swing.JRadioButton jRadioButtonReportsForCourses;
    private javax.swing.JRadioButton jRadioButtonReportsGeneral;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
