/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.Editar;

import dao.DaoCurso;
import dao.DaoUsuario;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import modelo.CursoEntity;
import modelo.Usuario;

/**
 *
 * @author nini2
 */
public class CursoEditar extends javax.swing.JFrame {

    CursoEntity curso;
    CursoEntity usuCurso;
    /**
     * Creates new form DatosPersonales
     */
    public CursoEditar() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Datos del usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2C = new javax.swing.JLabel();
        jLabel5C = new javax.swing.JLabel();
        jTxtCurso = new javax.swing.JTextField();
        jBtn_ModificarCurso = new javax.swing.JButton();
        jLblRetroceder = new javax.swing.JLabel();
        Jcb_DirigidoCurso = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5C1 = new javax.swing.JLabel();
        Jcb_EstadoCurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(228, 244, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2C.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2C.setText("Nombre");
        jPanel1.add(jLabel2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel5C.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5C.setText("Estado");
        jPanel1.add(jLabel5C, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jTxtCurso.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTxtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCursoActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 220, -1));

        jBtn_ModificarCurso.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtn_ModificarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jBtn_ModificarCurso.setText("Guardar");
        jBtn_ModificarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ModificarCursoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_ModificarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jLblRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retroceso.png"))); // NOI18N
        jPanel1.add(jLblRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Jcb_DirigidoCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niño", "Padre", "Madre", "Ambos Padres" }));
        Jcb_DirigidoCurso.setToolTipText("");
        jPanel1.add(Jcb_DirigidoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 220, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Editar Curso");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel5C1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5C1.setText("Dirigido");
        jPanel1.add(jLabel5C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        Jcb_EstadoCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        Jcb_EstadoCurso.setToolTipText("");
        jPanel1.add(Jcb_EstadoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjBtn_ModificarCurso() {
        return jBtn_ModificarCurso;
    }

    public void setjBtn_ModificarCurso(JButton jBtn_ModificarCurso) {
        this.jBtn_ModificarCurso = jBtn_ModificarCurso;
    }

    

    public JComboBox  getJcb_EstadoCurso() {
        return Jcb_DirigidoCurso;
    }

    public void setJcb_EstadoCurso(JComboBox<String> Jcb_EstadoCurso) {
        this.Jcb_DirigidoCurso = Jcb_EstadoCurso;
    }

    public JTextField getjTxtCurso() {
        return jTxtCurso;
    }

    public JComboBox<String> getJcb_DirigidoCurso() {
        return Jcb_DirigidoCurso;
    }

    public void setJcb_DirigidoCurso(JComboBox<String> Jcb_DirigidoCurso) {
        this.Jcb_DirigidoCurso = Jcb_DirigidoCurso;
    } 

    public JLabel getjLblRetroceder() {
        return jLblRetroceder;
    }

    public void setjLblRetroceder(JLabel jLblRetroceder) {
        this.jLblRetroceder = jLblRetroceder;
    }

    

    public boolean editarCurso(CursoEntity cur) {
        curso = cur;
        boolean estado;
        String estadeestrean;
         
        boolean verif = false;
        
        String dirigido;
       
        
       
        estadeestrean= (String) Jcb_EstadoCurso.getSelectedItem();
        if (estadeestrean.equals("Activo")){
            estado = true;
        }else{
            estado= false;
        }
        
        dirigido = Jcb_DirigidoCurso.getSelectedItem().toString();
        
        if (jTxtCurso.getText().equalsIgnoreCase(curso.getNombre())&&
            estado== curso.isEstado() && dirigido.equals(curso.getDirigido())){
            int opcion = JOptionPane.YES_NO_OPTION;
            JOptionPane.showMessageDialog(null,"Los datos son los mismos que estan registrados, si desea modificarlos debe cambiarlos. Quiere modificar los datos? ","Sistema" ,JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            if((jTxtCurso.getText().equalsIgnoreCase(""))){
                JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios, agregar valores ", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }else{
                nuevosDatosCurso(estado,dirigido);
                DaoCurso daocur= new  DaoCurso();
                verif = daocur.modificar(usuCurso);
//                if (verif==true) {
//                JOptionPane.showMessageDialog(null,"Los datos fueron modificados","Sistema" ,JOptionPane.PLAIN_MESSAGE);
//                vistEditarUsu.setVisible(false);
//                }else{
//                    JOptionPane.showMessageDialog(null, "Los datos no fueron modificados", "Error", JOptionPane.WARNING_MESSAGE);
//                }
            }
            
        }
        return verif;
    }

    private void nuevosDatosCurso(boolean valEstado,String dirigido) {
        usuCurso = new CursoEntity();
        usuCurso.setId(curso.getId());
        usuCurso.setNombre(jTxtCurso.getText());
        usuCurso.setDirigido(dirigido);
        usuCurso.setEstado(valEstado);
      
    }
    
    private void jBtn_ModificarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ModificarCursoActionPerformed
//        verLista_Usuario();
//        this.setVisible(false);
    }//GEN-LAST:event_jBtn_ModificarCursoActionPerformed

    private void jTxtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCursoActionPerformed

    public void verLista_Usuario(){
//        vista.List_Usuario btnIngresarMen = new vista.List_Usuario();
//        btnIngresarMen.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Jcb_DirigidoCurso;
    public javax.swing.JComboBox<String> Jcb_EstadoCurso;
    private javax.swing.JButton jBtn_ModificarCurso;
    private javax.swing.JLabel jLabel2C;
    private javax.swing.JLabel jLabel5C;
    private javax.swing.JLabel jLabel5C1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblRetroceder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtCurso;
    // End of variables declaration//GEN-END:variables
}
