/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Editar;


import com.toedter.calendar.JDateChooser;
import dao.DaoBeneficiario;
import dao.DaoPadres;
import dao.DaoSocioEconomico;
import dao.DaoEscolaridad;
import dao.DaoMama;
import dao.DaoPapa;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import modelo.Reg_Benf;
import java.util.Date;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Mama;
import modelo.Padres;
import modelo.Papa;
import modelo.Reg_Escolar;
import modelo.Reg_dataSocial;



/**
 *
 * @author steve
 */
public class DatosEditar extends javax.swing.JFrame {
    Reg_Benf benefi;
    Reg_Benf nuevBenefi = new Reg_Benf();
    Mama mama = new Mama();
    Papa papa = new Papa();
    Reg_Escolar escolar = new Reg_Escolar();
    Reg_dataSocial social= new Reg_dataSocial();
    DaoBeneficiario daoBenefi= new DaoBeneficiario();
    DaoSocioEconomico daoSocioEco = new DaoSocioEconomico();
    DaoPadres daopadres = new DaoPadres();
    DaoMama daomama = new DaoMama();
    DaoPapa daopapa = new DaoPapa();
    DaoEscolaridad DaoEscolaridad = new DaoEscolaridad();
    Padres padres = new Padres();

    /**
     * Creates new form Ins_Personal
     */
    public DatosEditar() {
        initComponents();
        setTitle("Datos del Beneficiario ");
        setLocationRelativeTo(null);        
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btg_problemaSalud = new javax.swing.ButtonGroup();
        Btg_escolaridadNivel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLblRetroceder = new javax.swing.JLabel();
        Jbtn_guardarEdit = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Jtf_ApellidosBenefi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Jtf_NombresBenefi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jtf_CedulaBenefi = new javax.swing.JTextField();
        Jcb_Religion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Jtf_CorreoBenefi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Jtf_edadBenefi = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Jtf_DirecBenefi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Jtf_convivienteBenefi = new javax.swing.JTextField();
        jLabelCelular = new javax.swing.JLabel();
        Jtf_celularBenefi = new javax.swing.JTextField();
        jTxtFechaNac = new javax.swing.JTextField();
        jTxtDiscapacidad = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        Jtf_NombreDocente = new javax.swing.JTextField();
        Jtf_DireEscolar = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        Jtf_NombInst = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        JRB_primaria = new javax.swing.JRadioButton();
        JRB_secundaria = new javax.swing.JRadioButton();
        jCmBGrado = new javax.swing.JComboBox();
        Jtf_Cel = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        Jtf_OtrosIngresos = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        Jtf_TotalIngresos = new javax.swing.JTextField();
        Jtf_gastos = new javax.swing.JTextField();
        JCB_sustento = new javax.swing.JComboBox<>();
        JCB_tipoTrabajo = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Jtf_nombreMama = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        Jcb_EstadoMama = new javax.swing.JComboBox<>();
        jLabel57 = new javax.swing.JLabel();
        Jtf_TelefMama = new javax.swing.JTextField();
        Jtf_lugar_trabMama = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        Jtf_CargoMama = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Jtf_nombrePapa = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Jtf_lugar_trabPapa = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        Jtf_CargoPapa = new javax.swing.JTextField();
        Jtf_TelefPapa = new javax.swing.JTextField();
        Jcb_EstadoPapa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(228, 244, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 2000));
        jPanel1.setLayout(null);

        jLblRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retroceso.png"))); // NOI18N
        jPanel1.add(jLblRetroceder);
        jLblRetroceder.setBounds(0, 0, 50, 50);

        Jbtn_guardarEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Jbtn_guardarEdit.setForeground(new java.awt.Color(51, 51, 51));
        Jbtn_guardarEdit.setText("Guardar");
        Jbtn_guardarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardarEditJbtn_guardarDatoSoecoActionPerformed(evt);
            }
        });
        jPanel1.add(Jbtn_guardarEdit);
        Jbtn_guardarEdit.setBounds(400, 350, 450, 36);

        jPanel3.setBackground(new java.awt.Color(228, 244, 251));
        jPanel3.setPreferredSize(new java.awt.Dimension(1350, 2800));

        Jtf_ApellidosBenefi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_ApellidosBenefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_ApellidosBenefiActionPerformed(evt);
            }
        });
        Jtf_ApellidosBenefi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_ApellidosBenefiKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Apellidos:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Nombres:");

        Jtf_NombresBenefi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_NombresBenefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_NombresBenefiActionPerformed(evt);
            }
        });
        Jtf_NombresBenefi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_NombresBenefiKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("Cédula:");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setText("Religión:");

        Jtf_CedulaBenefi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_CedulaBenefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_CedulaBenefiActionPerformed(evt);
            }
        });

        Jcb_Religion.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jcb_Religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actualizar", "Cristiano", "Católico", "Ateo", "Testigo de Jehová" }));
        Jcb_Religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcb_ReligionActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setText("Fecha de nacimiento:");

        Jtf_CorreoBenefi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_CorreoBenefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_CorreoBenefiActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel12.setText("Datos del beneficiario ");

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel26.setText("Correo:");

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel29.setText("Edad:");

        Jtf_edadBenefi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_edadBenefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_edadBenefiActionPerformed(evt);
            }
        });
        Jtf_edadBenefi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_edadBenefiKeyTyped(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel30.setText("Discapacidad:");

        Jtf_DirecBenefi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_DirecBenefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_DirecBenefiActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setText("Dirección:");

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel27.setText("Convivientes:");

        Jtf_convivienteBenefi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_convivienteBenefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_convivienteBenefiActionPerformed(evt);
            }
        });
        Jtf_convivienteBenefi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_convivienteBenefiKeyTyped(evt);
            }
        });

        jLabelCelular.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelCelular.setText("Celular:");

        Jtf_celularBenefi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_celularBenefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_celularBenefiActionPerformed(evt);
            }
        });

        jTxtFechaNac.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jTxtDiscapacidad.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(jLabel12)
                .addContainerGap(340, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel26)
                            .addComponent(jLabel8)
                            .addComponent(jLabelCelular))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Jtf_CedulaBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jtf_edadBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Jtf_DirecBenefi)
                                .addComponent(Jtf_NombresBenefi)
                                .addComponent(Jtf_CorreoBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Jtf_celularBenefi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(Jtf_convivienteBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtFechaNac))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jtf_ApellidosBenefi)
                            .addComponent(Jcb_Religion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtDiscapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtf_CedulaBenefi)
                    .addComponent(Jtf_edadBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jtf_ApellidosBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jtf_NombresBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jcb_Religion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jtf_CorreoBenefi)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jtf_DirecBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(Jtf_convivienteBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Jtf_celularBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Datos del Beneficiario ", jPanel3);

        jPanel7.setBackground(new java.awt.Color(228, 244, 251));
        jPanel7.setToolTipText("");

        jLabel48.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel48.setText("Datos Escolares");

        jLabel50.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel50.setText("Direccion escolar:");

        jLabel51.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel51.setText("Nombre de la  institución:"); // NOI18N

        jLabel52.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel52.setText("Nombre del docente:");

        Jtf_NombreDocente.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_NombreDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_NombreDocenteJtf_OtrosIngresosActionPerformed(evt);
            }
        });
        Jtf_NombreDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_NombreDocenteKeyTyped(evt);
            }
        });

        Jtf_DireEscolar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_DireEscolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_DireEscolarJtf_TotalIngresos1ActionPerformed(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel54.setText("Grado:"); // NOI18N

        Jtf_NombInst.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_NombInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_NombInstJtf_FijoActionPerformed(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel55.setText("Nivel escolar:");

        JRB_primaria.setBackground(new java.awt.Color(228, 244, 251));
        Btg_escolaridadNivel.add(JRB_primaria);
        JRB_primaria.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JRB_primaria.setText("Primaria");
        JRB_primaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JRB_primariaMouseClicked(evt);
            }
        });
        JRB_primaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_primariaActionPerformed(evt);
            }
        });

        JRB_secundaria.setBackground(new java.awt.Color(228, 244, 251));
        Btg_escolaridadNivel.add(JRB_secundaria);
        JRB_secundaria.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JRB_secundaria.setText("Secundaria");
        JRB_secundaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JRB_secundariaMouseClicked(evt);
            }
        });
        JRB_secundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_secundariaActionPerformed(evt);
            }
        });

        jCmBGrado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCmBGrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7 mo ", "8 vo", "9 no" }));

        Jtf_Cel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Cel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_CelJtf_TotalIngresosActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel53.setText("Teléfono:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(jLabel51)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Jtf_DireEscolar)
                    .addComponent(Jtf_NombInst)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(JRB_primaria, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JRB_secundaria))
                            .addComponent(Jtf_NombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addComponent(jLabel54))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmBGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jtf_Cel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(314, 314, 314))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(jLabel48)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(Jtf_NombInst, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRB_primaria)
                    .addComponent(JRB_secundaria)
                    .addComponent(jLabel54)
                    .addComponent(jCmBGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtf_NombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jtf_Cel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtf_DireEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addGap(98, 98, 98)
                .addComponent(jLabel49)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Datos Escolares", jPanel7);

        jPanel4.setBackground(new java.awt.Color(228, 244, 251));
        jPanel4.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel20.setText("Datos Socioeconómicos");

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel24.setText("Personas que sustentan el hogar:");

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel25.setText("Tipo de trabajo:");

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel28.setText("Gastos mensuales:");

        jLabel46.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel46.setText("Otros:");

        Jtf_OtrosIngresos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_OtrosIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_OtrosIngresosActionPerformed(evt);
            }
        });
        Jtf_OtrosIngresos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_OtrosIngresosKeyTyped(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel47.setText("Total de ingresos:");

        Jtf_TotalIngresos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_TotalIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TotalIngresosActionPerformed(evt);
            }
        });

        Jtf_gastos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_gastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_gastosJtf_TotalIngresos1ActionPerformed(evt);
            }
        });
        Jtf_gastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_gastosKeyTyped(evt);
            }
        });

        JCB_sustento.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        JCB_sustento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madre", "Padre", " " }));

        JCB_tipoTrabajo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        JCB_tipoTrabajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actualizar", "Fijo", "Propio", "Esporadico" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(1178, 1178, 1178))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(438, 438, 438)
                                .addComponent(jLabel20))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JCB_sustento, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(Jtf_gastos))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(JCB_tipoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jtf_OtrosIngresos))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(43, 43, 43)
                                .addComponent(Jtf_TotalIngresos)))))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCB_sustento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(JCB_tipoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(Jtf_OtrosIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(Jtf_TotalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtf_gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(122, 122, 122)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Datos SocioEconomicos", jPanel4);

        jPanel5.setBackground(new java.awt.Color(228, 244, 251));
        jPanel5.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel22.setText("Datos de Madre");

        Jtf_nombreMama.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_nombreMama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_nombreMamaJtf_FijoActionPerformed(evt);
            }
        });
        Jtf_nombreMama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_nombreMamaKeyTyped(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel45.setText("Nombre y apellido:");

        jLabel56.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel56.setText("Estado civil:");

        Jcb_EstadoMama.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jcb_EstadoMama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Soltero", "Unión de hecho", "Divorciado", "Viudo", "Actualizar" }));

        jLabel57.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel57.setText("Teléfono:");

        Jtf_TelefMama.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_TelefMama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TelefMamaJtf_TotalIngresos1ActionPerformed(evt);
            }
        });

        Jtf_lugar_trabMama.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_lugar_trabMama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_lugar_trabMamaJtf_OtrosIngresosActionPerformed(evt);
            }
        });
        Jtf_lugar_trabMama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_lugar_trabMamaKeyTyped(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel58.setText("Lugar de trabajo:");

        jLabel59.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel59.setText("Cargo:");

        Jtf_CargoMama.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_CargoMama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_CargoMamaJtf_TotalIngresosActionPerformed(evt);
            }
        });
        Jtf_CargoMama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_CargoMamaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(815, 815, 815)
                        .addComponent(jLabel23))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jLabel22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel56)
                            .addComponent(jLabel58)
                            .addComponent(jLabel59))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Jtf_lugar_trabMama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(Jcb_EstadoMama, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jtf_TelefMama, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Jtf_nombreMama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jtf_CargoMama))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(Jtf_nombreMama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcb_EstadoMama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtf_TelefMama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtf_lugar_trabMama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(Jtf_CargoMama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel23)
                .addGap(123, 123, 123))
        );

        jTabbedPane2.addTab("Datos de Madre", jPanel5);

        jPanel6.setBackground(new java.awt.Color(228, 244, 251));
        jPanel6.setToolTipText("");

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel38.setText("Datos de Padre");

        jLabel40.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel40.setText("Teléfono:");

        jLabel41.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel41.setText("Nombre y apellido:");

        Jtf_nombrePapa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_nombrePapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_nombrePapaJtf_FijoActionPerformed(evt);
            }
        });
        Jtf_nombrePapa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_nombrePapaKeyTyped(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel42.setText("Estado civil:");

        jLabel43.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel43.setText("Lugar de trabajo:");

        Jtf_lugar_trabPapa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_lugar_trabPapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_lugar_trabPapaJtf_OtrosIngresosActionPerformed(evt);
            }
        });
        Jtf_lugar_trabPapa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_lugar_trabPapaKeyTyped(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel44.setText("Cargo:");

        Jtf_CargoPapa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_CargoPapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_CargoPapaJtf_TotalIngresosActionPerformed(evt);
            }
        });
        Jtf_CargoPapa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Jtf_CargoPapaKeyTyped(evt);
            }
        });

        Jtf_TelefPapa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_TelefPapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TelefPapaJtf_TotalIngresos1ActionPerformed(evt);
            }
        });

        Jcb_EstadoPapa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jcb_EstadoPapa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Soltero", "Unión de hecho", "Divorciado", "Viudo", "Actualizar" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Jtf_lugar_trabPapa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Jcb_EstadoPapa, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtf_TelefPapa, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jtf_nombrePapa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jtf_CargoPapa))
                .addGap(0, 239, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(842, 842, 842)
                        .addComponent(jLabel39))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(jLabel38)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(Jtf_nombrePapa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcb_EstadoPapa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtf_TelefPapa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtf_lugar_trabPapa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(Jtf_CargoPapa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel39)
                .addGap(136, 136, 136))
        );

        jTabbedPane2.addTab("Datos de Padre", jPanel6);

        jPanel1.add(jTabbedPane2);
        jTabbedPane2.setBounds(100, 40, 1050, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1266, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtf_edadBenefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_edadBenefiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_edadBenefiActionPerformed

    private void Jtf_CorreoBenefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_CorreoBenefiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_CorreoBenefiActionPerformed

    private void Jtf_CedulaBenefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_CedulaBenefiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_CedulaBenefiActionPerformed

    private void Jtf_NombresBenefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_NombresBenefiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_NombresBenefiActionPerformed

    private void Jtf_ApellidosBenefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_ApellidosBenefiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_ApellidosBenefiActionPerformed

    private void Jtf_DirecBenefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_DirecBenefiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_DirecBenefiActionPerformed

    private void Jcb_ReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcb_ReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcb_ReligionActionPerformed

    private void Jtf_convivienteBenefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_convivienteBenefiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_convivienteBenefiActionPerformed

    private void Jtf_edadBenefiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_edadBenefiKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente numeros");
        }
    }//GEN-LAST:event_Jtf_edadBenefiKeyTyped

    private void Jtf_convivienteBenefiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_convivienteBenefiKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente numeros");
        }
    }//GEN-LAST:event_Jtf_convivienteBenefiKeyTyped

    private void Jtf_NombresBenefiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_NombresBenefiKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente letras");
        }
    }//GEN-LAST:event_Jtf_NombresBenefiKeyTyped

    private void Jtf_ApellidosBenefiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_ApellidosBenefiKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente letras");
        }
    }//GEN-LAST:event_Jtf_ApellidosBenefiKeyTyped

    private void Jtf_celularBenefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_celularBenefiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_celularBenefiActionPerformed

    private void Jtf_TotalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TotalIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TotalIngresosActionPerformed

    private void Jtf_gastosJtf_TotalIngresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_gastosJtf_TotalIngresos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_gastosJtf_TotalIngresos1ActionPerformed

    private void Jtf_gastosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_gastosKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente numeros");
        }
    }//GEN-LAST:event_Jtf_gastosKeyTyped

    private void Jtf_NombreDocenteJtf_OtrosIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_NombreDocenteJtf_OtrosIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_NombreDocenteJtf_OtrosIngresosActionPerformed

    private void Jtf_NombreDocenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_NombreDocenteKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente letras");
        }
    }//GEN-LAST:event_Jtf_NombreDocenteKeyTyped

    private void Jtf_CelJtf_TotalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_CelJtf_TotalIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_CelJtf_TotalIngresosActionPerformed

    private void Jtf_DireEscolarJtf_TotalIngresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_DireEscolarJtf_TotalIngresos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_DireEscolarJtf_TotalIngresos1ActionPerformed

    private void Jtf_NombInstJtf_FijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_NombInstJtf_FijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_NombInstJtf_FijoActionPerformed

    private void JRB_primariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_primariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_primariaActionPerformed

    private void JRB_secundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_secundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB_secundariaActionPerformed

    private void Jbtn_guardarEditJbtn_guardarDatoSoecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardarEditJbtn_guardarDatoSoecoActionPerformed
        // TODO add your handling code here:

        //        agregarDatosSocialesEco();
        //        this.setVisible(false);

    }//GEN-LAST:event_Jbtn_guardarEditJbtn_guardarDatoSoecoActionPerformed

    private void Jtf_OtrosIngresosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_OtrosIngresosKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar unicamente numeros");
        }
    }//GEN-LAST:event_Jtf_OtrosIngresosKeyTyped

    private void Jtf_OtrosIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_OtrosIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_OtrosIngresosActionPerformed

    private void JRB_primariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JRB_primariaMouseClicked
        escolar.setBen_escolaridad(JRB_primaria.getLabel());
    }//GEN-LAST:event_JRB_primariaMouseClicked

    private void JRB_secundariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JRB_secundariaMouseClicked
         escolar.setBen_escolaridad(JRB_primaria.getLabel());
    }//GEN-LAST:event_JRB_secundariaMouseClicked

    private void Jtf_CargoPapaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_CargoPapaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_CargoPapaKeyTyped

    private void Jtf_CargoPapaJtf_TotalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_CargoPapaJtf_TotalIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_CargoPapaJtf_TotalIngresosActionPerformed

    private void Jtf_lugar_trabPapaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_lugar_trabPapaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_lugar_trabPapaKeyTyped

    private void Jtf_lugar_trabPapaJtf_OtrosIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_lugar_trabPapaJtf_OtrosIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_lugar_trabPapaJtf_OtrosIngresosActionPerformed

    private void Jtf_TelefPapaJtf_TotalIngresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TelefPapaJtf_TotalIngresos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TelefPapaJtf_TotalIngresos1ActionPerformed

    private void Jtf_nombrePapaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_nombrePapaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_nombrePapaKeyTyped

    private void Jtf_nombrePapaJtf_FijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_nombrePapaJtf_FijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_nombrePapaJtf_FijoActionPerformed

    private void Jtf_nombreMamaJtf_FijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_nombreMamaJtf_FijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_nombreMamaJtf_FijoActionPerformed

    private void Jtf_nombreMamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_nombreMamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_nombreMamaKeyTyped

    private void Jtf_TelefMamaJtf_TotalIngresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TelefMamaJtf_TotalIngresos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TelefMamaJtf_TotalIngresos1ActionPerformed

    private void Jtf_lugar_trabMamaJtf_OtrosIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_lugar_trabMamaJtf_OtrosIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_lugar_trabMamaJtf_OtrosIngresosActionPerformed

    private void Jtf_lugar_trabMamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_lugar_trabMamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_lugar_trabMamaKeyTyped

    private void Jtf_CargoMamaJtf_TotalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_CargoMamaJtf_TotalIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_CargoMamaJtf_TotalIngresosActionPerformed

    private void Jtf_CargoMamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_CargoMamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_CargoMamaKeyTyped
      
//    public void inscribirNavegacion(){
//        Ins_Curso_per btncurso = new Ins_Curso_per();
//        btncurso.setVisible(true);
//        
//    }
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosEditar().setVisible(true);
                
            }
        });
    } 

    public JButton getJbtn_guardarEdit() {
        return Jbtn_guardarEdit;
    }

    public void setJbtn_guardarEdit(JButton Jbtn_guardarEdit) {
        this.Jbtn_guardarEdit = Jbtn_guardarEdit;
    }

    public JRadioButton getJRB_primaria() {
        return JRB_primaria;
    }

    public void setJRB_primaria(JRadioButton JRB_primaria) {
        this.JRB_primaria = JRB_primaria;
    }

    public JRadioButton getJRB_secundaria() {
        return JRB_secundaria;
    }

    public void setJRB_secundaria(JRadioButton JRB_secundaria) {
        this.JRB_secundaria = JRB_secundaria;
    }

    


    public JLabel getjLblRetroceder() {
        return jLblRetroceder;
    }

    public void setjLblRetroceder(JLabel jLblRetroceder) {
        this.jLblRetroceder = jLblRetroceder;
    }
    public void llenar(int num, DefaultTableModel modelo ) {
        benefi = new Reg_Benf();
        
        String cedula, nombr, ape, direc, telef;

        cedula = (String) modelo.getValueAt(num, 0);
        nombr = (String) modelo.getValueAt(num, 1);
        ape = (String) modelo.getValueAt(num, 2);
        direc = (String) modelo.getValueAt(num, 5);
        telef = (String) modelo.getValueAt(num, 6);
        benefi.setCedula(cedula);
        benefi.setNombre(nombr);
        benefi.setApellido(ape);
        benefi.setDireccion(direc);
        benefi.setTelefono(telef);
        
        benefi = daoBenefi.obtener(benefi);
        System.out.println(" id deberia" + benefi.getId_benf());
        Jtf_CedulaBenefi.setText(benefi.getCedula());
        Jtf_edadBenefi.setText(String.valueOf(benefi.getEdad()));
        
        Date date = benefi.getFech_nac();
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");  
        String strDate = dateFormat.format(date);  
        jTxtFechaNac.setText(strDate);
        Jtf_NombresBenefi.setText(benefi.getNombre());
        Jtf_ApellidosBenefi.setText(benefi.getApellido());
        Jtf_CorreoBenefi.setText(benefi.getCorreo());
        Jcb_Religion.setSelectedItem(benefi.getReligion());
        Jtf_DirecBenefi.setText(benefi.getDireccion());
        jTxtDiscapacidad.setText(benefi.getProm_sal());
        Jtf_celularBenefi.setText(benefi.getTelefono());
        Jtf_convivienteBenefi.setText(String.valueOf(benefi.getNum_conv()));
        
        //llenar parte escolar
        escolar.setId_escuela(benefi.getId_escu());
       
        escolar = DaoEscolaridad.obtenerDatos(escolar);
        Jtf_NombInst.setText(escolar.getBen_nomEsc());
        if(escolar.getBen_escolaridad().equals("Primaria")){
            JRB_primaria.setSelected(true);
            jCmBGrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Actualizar", "Inicial 1", "Inicial 2", "1ero Básica","2do Básica", 
                                                                                    "3ero Básica", "4to Básica", "5to Básica", "6to Básica", "7to Básica" }));
        }
        if(escolar.getBen_escolaridad().equals("Secundaria")){
            JRB_secundaria.setSelected(true);
            jCmBGrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Actualizar", "8vo EGB ", "9no EGB ", "10mo EGB", "1ero Bachillerato ", "2do Bachillerato ", "3ero Bachillerato" }));
        }
        jCmBGrado.setSelectedItem(escolar.getBen_grado());
        Jtf_Cel.setText(escolar.getBen_numprof());
        Jtf_NombreDocente.setText(escolar.getBen_nomprof());
        Jtf_DireEscolar.setText(escolar.getBen_dir());
        
        //llenar parte social
        social.setId_socioeconmico(benefi.getId_socioec());
        social = daoSocioEco.obtenerDatos(social);
        JCB_sustento.setSelectedItem(social.getPer_sustento());
        JCB_tipoTrabajo.setSelectedItem(social.getPer_tipo_trabajo());
        Jtf_OtrosIngresos.setText(social.getPer_otro_ingreso());
        Jtf_gastos.setText(social.getPer_gastomensual());
        
        
        //llenar parte padres
        padres.setId_padres(benefi.getId_padres());
        padres = daopadres.obtenerDatos(padres);
        Jtf_TotalIngresos.setText(padres.getIng_econ());
        mama.setId_mama(padres.getId_mama());
        mama = daomama.obtenerDato(mama);
        Jtf_nombreMama.setText(mama.getNombre());
        Jcb_EstadoMama.setSelectedItem(mama.getEst_civ_ma());
        Jtf_TelefMama.setText(mama.getTelefono());
        Jtf_lugar_trabMama.setText(mama.getLug_tra_ma());
        Jtf_CargoMama.setText(mama.getCargo_ma());
        
        
        papa.setId_papa(padres.getId_papa());
        papa = daopapa.obtenerDato(papa);
        Jtf_nombrePapa.setText(papa.getNombre());
        Jcb_EstadoPapa.setSelectedItem(papa.getEst_civ_pa());
        Jtf_TelefPapa.setText(papa.getTelefono());
        Jtf_lugar_trabPapa.setText(papa.getLug_tra_pa());
        Jtf_CargoPapa.setText(papa.getCargo_pa());
    }

    

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Btg_escolaridadNivel;
    private javax.swing.ButtonGroup Btg_problemaSalud;
    private javax.swing.JComboBox<String> JCB_sustento;
    private javax.swing.JComboBox<String> JCB_tipoTrabajo;
    private javax.swing.JRadioButton JRB_primaria;
    private javax.swing.JRadioButton JRB_secundaria;
    private javax.swing.JButton Jbtn_guardarEdit;
    private javax.swing.JComboBox<String> Jcb_EstadoMama;
    private javax.swing.JComboBox<String> Jcb_EstadoPapa;
    private javax.swing.JComboBox<String> Jcb_Religion;
    private javax.swing.JTextField Jtf_ApellidosBenefi;
    private javax.swing.JTextField Jtf_CargoMama;
    private javax.swing.JTextField Jtf_CargoPapa;
    private javax.swing.JTextField Jtf_CedulaBenefi;
    private javax.swing.JTextField Jtf_Cel;
    private javax.swing.JTextField Jtf_CorreoBenefi;
    private javax.swing.JTextField Jtf_DireEscolar;
    private javax.swing.JTextField Jtf_DirecBenefi;
    private javax.swing.JTextField Jtf_NombInst;
    private javax.swing.JTextField Jtf_NombreDocente;
    private javax.swing.JTextField Jtf_NombresBenefi;
    private javax.swing.JTextField Jtf_OtrosIngresos;
    private javax.swing.JTextField Jtf_TelefMama;
    private javax.swing.JTextField Jtf_TelefPapa;
    private javax.swing.JTextField Jtf_TotalIngresos;
    private javax.swing.JTextField Jtf_celularBenefi;
    private javax.swing.JTextField Jtf_convivienteBenefi;
    private javax.swing.JTextField Jtf_edadBenefi;
    private javax.swing.JTextField Jtf_gastos;
    private javax.swing.JTextField Jtf_lugar_trabMama;
    private javax.swing.JTextField Jtf_lugar_trabPapa;
    private javax.swing.JTextField Jtf_nombreMama;
    private javax.swing.JTextField Jtf_nombrePapa;
    private javax.swing.JComboBox jCmBGrado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLblRetroceder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTxtDiscapacidad;
    private javax.swing.JTextField jTxtFechaNac;
    // End of variables declaration//GEN-END:variables

    public boolean editarBenefi() {
        boolean valorbenefi = false;
        boolean valorescu = false;
        boolean valorsocio = false;
        boolean valorpa= false;
        boolean valorma = false;
        
        SimpleDateFormat  formato = new SimpleDateFormat("dd-MM-yyyy"); 
        try {
            Date date = formato.parse(jTxtFechaNac.getText());
            nuevBenefi.setFech_nac(date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El campo fecha de nacimiento debe tener el formato dd-MM-yyyy", "Error", JOptionPane.WARNING_MESSAGE);
        }
        nuevBenefi.setId_benf(benefi.getId_benf());
        nuevBenefi.setCedula(Jtf_CedulaBenefi.getText());
        nuevBenefi.setEdad(Integer.valueOf(Jtf_edadBenefi.getText()));
        nuevBenefi.setNombre(Jtf_NombresBenefi.getText());
        nuevBenefi.setApellido(Jtf_ApellidosBenefi.getText());
        nuevBenefi.setCorreo(Jtf_CorreoBenefi.getText());
        nuevBenefi.setReligion((String)Jcb_Religion.getSelectedItem());
        nuevBenefi.setDireccion(Jtf_DirecBenefi.getText());
        nuevBenefi.setProm_sal(jTxtDiscapacidad.getText());
        nuevBenefi.setTelefono(Jtf_celularBenefi.getText());
        nuevBenefi.setNum_conv(Integer.valueOf(Jtf_convivienteBenefi.getText()));
        nuevBenefi.setId_escu(Integer.valueOf(benefi.getId_escu()));
        nuevBenefi.setId_padres(Integer.valueOf(benefi.getId_padres()));
        nuevBenefi.setId_socioec(Integer.valueOf(benefi.getId_socioec()));
        valorbenefi = daoBenefi.modificar(nuevBenefi);
        
        escolar.setId_escuela(Integer.valueOf(benefi.getId_escu()));
        System.out.println("escolaridad "+ escolar.getBen_escolaridad());
        escolar.setBen_nomEsc(Jtf_NombInst.getText());
        escolar.setBen_grado((String) jCmBGrado.getSelectedItem());
        escolar.setBen_nomprof(Jtf_NombreDocente.getText());
        escolar.setBen_numprof(Jtf_Cel.getText());
        escolar.setBen_dir(Jtf_DireEscolar.getText());
        valorescu = DaoEscolaridad.modificar(escolar);
        
        social.setId_socioeconmico(benefi.getId_socioec());
        social.setPer_sustento((String) JCB_sustento.getSelectedItem());
        social.setPer_tipo_trabajo((String)JCB_tipoTrabajo.getSelectedItem());
        social.setPer_otro_ingreso(Jtf_OtrosIngresos.getText());
        social.setPer_gastomensual(Jtf_gastos.getText());
        valorsocio = daoSocioEco.modificar(social);
        
        padres.setIng_econ(Jtf_TotalIngresos.getText());
        daopadres.modificar(padres);
        
        mama.setNombre(Jtf_nombreMama.getText());
        mama.setEst_civ_ma((String)Jcb_EstadoMama.getSelectedItem());
        mama.setLug_tra_ma(Jtf_lugar_trabMama.getText());
        mama.setCargo_ma(Jtf_CargoMama.getText());
        mama.setTelefono(Jtf_TelefMama.getText());
        valorma = daomama.modificar(mama);
        
//        papa.setId_papa(benefi.getId_socioec());
        papa.setNombre(Jtf_nombrePapa.getText());
        papa.setEst_civ_pa((String)Jcb_EstadoPapa.getSelectedItem());
        papa.setLug_tra_pa(Jtf_lugar_trabPapa.getText());
        papa.setCargo_pa(Jtf_CargoPapa.getText());
        papa.setTelefono(Jtf_TelefPapa.getText());
        valorpa = daopapa.modificar(papa);
        
        if (valorbenefi || valorescu  || valorsocio || valorma || valorpa ){
            valorbenefi = true;
        }else{
            valorbenefi = false;
            JOptionPane.showMessageDialog(null,"Ocurrio un problema ");
        }
       
        return valorbenefi;
    }

    public void llenarGrdPrima() {
        jCmBGrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Actualizar", "Inicial 1", "Inicial 2", "1ero Básica","2do Básica", 
                                                                                    "3ero Básica", "4to Básica", "5to Básica", "6to Básica", "7to Básica" }));
    }

    public void llenarGrdSecun() {
        jCmBGrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Actualizar", "8vo EGB ", "9no EGB ", "10mo EGB", "1ero Bachillerato ",
                                                                                "2do Bachillerato ", "3ero Bachillerato" }));
    }
}
